name: ci
on:
  push:
#    branches: main
jobs:
  docker-image-transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: run linux command
        run: |
          echo "Hostname: "`hostname`
          echo "Kernel info: "`uname -a`  
          echo "Current path: "`pwd`
          echo "ls : "`ls -al `
      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker retag k8s image
        run: |
          bash k8s-image-retag.sh
      - name: query docker images
        run: docker images
