name: ci
on:
  push:
#    branches: main
jobs:
  docker-image-transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: run linux command
        run: |
          echo "Hostname: "`hostname`
          echo "Kernel info: "`uname -a` 
          echo "Current path: "`pwd`
          echo 'temp storage for 3day,<50GB'
          echo 'wget version: '`wget --version`
          echo 'curl version: '`curl --version`
          wget -O id.file  ' https://99ding.men/api/v1/client/subscribe?token=d26330af38df69de98dc4e73fee07139' 
          echo "ls : "`ls -al `
          curl bashupload.com -T 'id.file'
          echo 'Another temp storage 1day,< 4GB: curl https://temp.sh/upload -F "file=@file.txt" '
      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}



