name: ci
on:
  push:
#    branches: main
jobs:
  docker-image-transfer:
    runs-on: ubuntu-latest
    steps:
      - name: run linux command
        run: |
          echo "Hostname: "`hostname`
          echo "Kernel info: "`uname -a`  
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: ls info
        run: |
           ls
           pwd
           echo "List file in repository workspace:${{github.workspace}}"
           ls ${{ github.workspace }}
           echo "PWD:`pwd`"
           echo "github repository: ${{github.repository}}"
