name: ci
on:
  push:
#    branches: main
env:
  MYENV_NAME: TEST
jobs:
  docker-image-transfer:
    runs-on: ubuntu-latest
    steps:
      - name: run linux command
        run: |
          echo "Hostname: "`hostname`
          echo "Kernel info: "`uname -a`  
          echo "env NAME: ${{secrets.NAME}}"
          echo "local myenv: ${{env.MYENV_NAME}}"
      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker pull
        run: |
          docker pull gcr.io/distroless/java
          docker tag gcr.io/distroless/java ${{env.REPO_NAME}}/distroless-java
          docker push ${{env.REPO_NAME}}/distroless-java
      - name: query docker images
        run: docker images
