name: ci
on:
  push:
#    branches: main
jobs:
  docker-image-transfer:
    runs-on: ubuntu-latest
    steps:
      - name: run linux command
        run: |
          echo "Hostname: "`hostname`
          echo "Kernel info: "`uname -a`  
      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker pull
        run: |
          docker pull k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          docker tag k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2 276912053/nfs-subdir-external-provisioner:v4.0.2
          docker push 276912053/nfs-subdir-external-provisioner:v4.0.2
      - name: query docker images
        run: docker images
